name: "ui_portfolio"
description: "This my UI portfolio website host in GitHub pages."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  outlined_text: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/af.png
    - assets/images/af2.png
    - assets/images/designer_ill.png
    - assets/images/sb.png
    - assets/icons/Adobe_XD.png
    - assets/icons/Figma.png
    - assets/icons/Flutter.png
    - assets/icons/GitHub.png
    - assets/icons/LinkedIn.png
    - assets/icons/Python.png

  fonts:
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
    - family: JosefinSlab
      fonts:
        - asset: assets/fonts/JosefinSlab-Regular.ttf
